version: '3.8'
services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: smyc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      target: dev
    volumes:
      - .:/app
    command: [ "mvn", "spring-boot:run", "-Dspring-boot.run.profiles=dev" ]
    ports:
      - "8080:8080"
      - "35729:35729"
    environment:
      SPRING_PROFILES_ACTIVE: dev

volumes:
  pgdata: